[build]
  command = "npm ci && npm run build --workspace=frontend"
  publish = "frontend/.output/public"

[functions]
  directory = "frontend/.netlify/functions-internal"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000