[build]
  command = "npm ci && cd frontend && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "frontend/.netlify/functions-internal"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000